#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/exchange_rate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: admin

spring:
  datasource:
    url: jdbc:h2:mem:exchange_rate_db
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    properties:
      hibernate:
       #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

