spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange_rate_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin

  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
